name = "SolverLogging"
uuid = "c2e08473-88be-4f39-9d3c-afcdb6e3aeb8"
authors = ["Brian Jackson <bjack205@gmail.com>"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Formatting = "0.4"
julia="1"
